
package au.edu.unsw.assi.soapservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-09-01T16:16:27.765+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "importDownloadFault", targetNamespace = "http://soapservice.assi.unsw.edu.au")
public class ImportDownloadFaultMsg extends Exception {
    
    private au.edu.unsw.assi.soapservice.ImportDownloadFault importDownloadFault;

    public ImportDownloadFaultMsg() {
        super();
    }
    
    public ImportDownloadFaultMsg(String message) {
        super(message);
    }
    
    public ImportDownloadFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ImportDownloadFaultMsg(String message, au.edu.unsw.assi.soapservice.ImportDownloadFault importDownloadFault) {
        super(message);
        this.importDownloadFault = importDownloadFault;
    }

    public ImportDownloadFaultMsg(String message, au.edu.unsw.assi.soapservice.ImportDownloadFault importDownloadFault, Throwable cause) {
        super(message, cause);
        this.importDownloadFault = importDownloadFault;
    }

    public au.edu.unsw.assi.soapservice.ImportDownloadFault getFaultInfo() {
        return this.importDownloadFault;
    }
}
