
package au.edu.unsw.soacourse.marketdatautilservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-10-05T19:02:53.400+11:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "convertMarketDataFault", targetNamespace = "http://marketdatautilservice.soacourse.unsw.edu.au")
public class ConvertMarketDataFaultMsg extends Exception {
    
    private au.edu.unsw.soacourse.marketdatautilservice.ServiceFaultType convertMarketDataFault;

    public ConvertMarketDataFaultMsg() {
        super();
    }
    
    public ConvertMarketDataFaultMsg(String message) {
        super(message);
    }
    
    public ConvertMarketDataFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ConvertMarketDataFaultMsg(String message, au.edu.unsw.soacourse.marketdatautilservice.ServiceFaultType convertMarketDataFault) {
        super(message);
        this.convertMarketDataFault = convertMarketDataFault;
    }

    public ConvertMarketDataFaultMsg(String message, au.edu.unsw.soacourse.marketdatautilservice.ServiceFaultType convertMarketDataFault, Throwable cause) {
        super(message, cause);
        this.convertMarketDataFault = convertMarketDataFault;
    }

    public au.edu.unsw.soacourse.marketdatautilservice.ServiceFaultType getFaultInfo() {
        return this.convertMarketDataFault;
    }
}
