package au.edu.unsw.soacourse.soapcurrencyconvert;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-09-05T17:32:04.674+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://soapcurrencyconvert.soacourse.unsw.edu.au", name = "SOAPCurrencyConvertService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SOAPCurrencyConvertService {

    @WebResult(name = "ExchangeRateResponse", targetNamespace = "http://soapcurrencyconvert.soacourse.unsw.edu.au", partName = "parameters")
    @WebMethod(action = "http://soapcurrencyconvert.soacourse.unsw.edu.au/yahooExchangeRate")
    public ExchangeRateResponse yahooExchangeRate(
        @WebParam(partName = "parameters", name = "ExchangeRateRequest", targetNamespace = "http://soapcurrencyconvert.soacourse.unsw.edu.au")
        ExchangeRateRequest parameters
    ) throws ExchangeRateFaultMsg;
}
