package au.edu.unsw.soacourse.marketdatautilservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-09-01T14:36:25.877+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://marketdatautilservice.soacourse.unsw.edu.au", name = "MarketDataUtilService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MarketDataUtilService {

    @WebResult(name = "convertMarketDataResponse", targetNamespace = "http://marketdatautilservice.soacourse.unsw.edu.au", partName = "parameters")
    @WebMethod(action = "http://marketdatautilservice.soacourse.unsw.edu.au/convertMarketData")
    public ConvertMarketDataResponse convertMarketData(
        @WebParam(partName = "parameters", name = "convertMarketDataRequest", targetNamespace = "http://marketdatautilservice.soacourse.unsw.edu.au")
        ConvertMarketDataRequest parameters
    ) throws ConvertMarketDataFaultMsg;

    @WebResult(name = "summaryMarketDataResponse", targetNamespace = "http://marketdatautilservice.soacourse.unsw.edu.au", partName = "parameters")
    @WebMethod(action = "http://marketdatautilservice.soacourse.unsw.edu.au/summaryMarketData")
    public SummaryMarketDataResponse summaryMarketData(
        @WebParam(partName = "parameters", name = "summaryMarketDataRequest", targetNamespace = "http://marketdatautilservice.soacourse.unsw.edu.au")
        SummaryMarketDataRequest parameters
    ) throws SummaryMarketDataFaultMsg;
}
