package au.edu.unsw.assi.soapservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-09-01T19:45:25.729+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://soapservice.assi.unsw.edu.au", name = "Service1")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Service1 {

    @WebResult(name = "downloadFileResponse", targetNamespace = "http://soapservice.assi.unsw.edu.au", partName = "parameters")
    @WebMethod(action = "http://soapservice.assi.unsw.edu.au/downloadFile")
    public DownloadFileResponse downloadFile(
        @WebParam(partName = "parameters", name = "downloadFileRequest", targetNamespace = "http://soapservice.assi.unsw.edu.au")
        DownloadFileRequest parameters
    ) throws ImportDownloadFaultMsg;

    @WebResult(name = "importMarketDataResponse", targetNamespace = "http://soapservice.assi.unsw.edu.au", partName = "parameters")
    @WebMethod(action = "http://soapservice.assi.unsw.edu.au/importMarketData")
    public ImportMarketDataResponse importMarketData(
        @WebParam(partName = "parameters", name = "importMarketDataRequest", targetNamespace = "http://soapservice.assi.unsw.edu.au")
        ImportMarketDataRequest parameters
    ) throws ImportDownloadFaultMsg;
}
