
package au.edu.unsw.soacourse.soapcurrencyconvert;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-08-31T21:47:24.517+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "ExchangeRateFault", targetNamespace = "http://soapcurrencyconvert.soacourse.unsw.edu.au")
public class ExchangeRateFaultMsg extends Exception {
    
    private au.edu.unsw.soacourse.soapcurrencyconvert.ServiceFaultType exchangeRateFault;

    public ExchangeRateFaultMsg() {
        super();
    }
    
    public ExchangeRateFaultMsg(String message) {
        super(message);
    }
    
    public ExchangeRateFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ExchangeRateFaultMsg(String message, au.edu.unsw.soacourse.soapcurrencyconvert.ServiceFaultType exchangeRateFault) {
        super(message);
        this.exchangeRateFault = exchangeRateFault;
    }

    public ExchangeRateFaultMsg(String message, au.edu.unsw.soacourse.soapcurrencyconvert.ServiceFaultType exchangeRateFault, Throwable cause) {
        super(message, cause);
        this.exchangeRateFault = exchangeRateFault;
    }

    public au.edu.unsw.soacourse.soapcurrencyconvert.ServiceFaultType getFaultInfo() {
        return this.exchangeRateFault;
    }
}
