package au.edu.unsw.soacourse.soapcurrencyconvert;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-08-31T21:47:24.519+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "SOAPCurrencyConvertServiceImplService", 
                  wsdlLocation = "http://localhost:8080/SOAPCurrencyConvertService/SOAPCurrencyConvertService?wsdl",
                  targetNamespace = "http://soapcurrencyconvert.soacourse.unsw.edu.au/") 
public class SOAPCurrencyConvertServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soapcurrencyconvert.soacourse.unsw.edu.au/", "SOAPCurrencyConvertServiceImplService");
    public final static QName SOAPCurrencyConvertServiceImplPort = new QName("http://soapcurrencyconvert.soacourse.unsw.edu.au/", "SOAPCurrencyConvertServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SOAPCurrencyConvertService/SOAPCurrencyConvertService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SOAPCurrencyConvertServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/SOAPCurrencyConvertService/SOAPCurrencyConvertService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SOAPCurrencyConvertServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SOAPCurrencyConvertServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAPCurrencyConvertServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SOAPCurrencyConvertServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SOAPCurrencyConvertServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SOAPCurrencyConvertServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns SOAPCurrencyConvertService
     */
    @WebEndpoint(name = "SOAPCurrencyConvertServiceImplPort")
    public SOAPCurrencyConvertService getSOAPCurrencyConvertServiceImplPort() {
        return super.getPort(SOAPCurrencyConvertServiceImplPort, SOAPCurrencyConvertService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SOAPCurrencyConvertService
     */
    @WebEndpoint(name = "SOAPCurrencyConvertServiceImplPort")
    public SOAPCurrencyConvertService getSOAPCurrencyConvertServiceImplPort(WebServiceFeature... features) {
        return super.getPort(SOAPCurrencyConvertServiceImplPort, SOAPCurrencyConvertService.class, features);
    }

}
