
package au.edu.unsw.soacourse.marketdatautilservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-09-01T19:45:26.153+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "summaryMarketDataFault", targetNamespace = "http://marketdatautilservice.soacourse.unsw.edu.au")
public class SummaryMarketDataFaultMsg extends Exception {
    
    private au.edu.unsw.soacourse.marketdatautilservice.ServiceFaultType summaryMarketDataFault;

    public SummaryMarketDataFaultMsg() {
        super();
    }
    
    public SummaryMarketDataFaultMsg(String message) {
        super(message);
    }
    
    public SummaryMarketDataFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public SummaryMarketDataFaultMsg(String message, au.edu.unsw.soacourse.marketdatautilservice.ServiceFaultType summaryMarketDataFault) {
        super(message);
        this.summaryMarketDataFault = summaryMarketDataFault;
    }

    public SummaryMarketDataFaultMsg(String message, au.edu.unsw.soacourse.marketdatautilservice.ServiceFaultType summaryMarketDataFault, Throwable cause) {
        super(message, cause);
        this.summaryMarketDataFault = summaryMarketDataFault;
    }

    public au.edu.unsw.soacourse.marketdatautilservice.ServiceFaultType getFaultInfo() {
        return this.summaryMarketDataFault;
    }
}
